In [ ]:
import pandas as pd

In [ ]:
import numpy as nm

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv('Iris.csv')

In [ ]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
print(df.columns)

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')


In [ ]:
X = df[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']]

In [ ]:
y=df['Species']

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25)

In [ ]:
print(y_train.shape)

(112,)


In [ ]:
print(y_test.shape)

(38,)


In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc=StandardScaler()

In [ ]:
X_train=sc.fit_transform(X_train)

In [ ]:
X_test=sc.transform(X_test)

In [ ]:
from sklearn.naive_bayes import GaussianNB

In [ ]:
NB=GaussianNB()

In [ ]:
NB.fit(X_train,y_train)

GaussianNB()

In [ ]:
y_pred=NB.predict(X_test)

In [ ]:
print(y_pred)

['Iris-virginica' 'Iris-setosa' 'Iris-virginica' 'Iris-setosa'
 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa'
 'Iris-setosa' 'Iris-virginica' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-virginica' 'Iris-setosa' 'Iris-setosa' 'Iris-virginica'
 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor' 'Iris-setosa'
 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica' 'Iris-setosa'
 'Iris-virginica' 'Iris-virginica' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica' 'Iris-versicolor']


In [ ]:
from sklearn.metrics import confusion_matrix,precision_score,accuracy_score,recall_score,classification_report

In [ ]:
cm=confusion_matrix(y_test,y_pred)

In [ ]:
print(cm)

[[14  0  0]
 [ 0 11  1]
 [ 0  3  9]]


In [ ]:
cr=classification_report(y_test,y_pred)

In [ ]:
print(cr)

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        14
Iris-versicolor       0.79      0.92      0.85        12
 Iris-virginica       0.90      0.75      0.82        12

       accuracy                           0.89        38
      macro avg       0.90      0.89      0.89        38
   weighted avg       0.90      0.89      0.89        38



In [ ]:
pr =precision_score(y_test,y_pred,average='micro')

In [ ]:
print(pr)

0.8947368421052632


In [ ]:
ac=accuracy_score(y_test,y_pred)

In [ ]:
print(ac)

0.8947368421052632


In [ ]:
rs=recall_score(y_test,y_pred,average='micro')

In [ ]:
print(rs)

0.8947368421052632


In [ ]:
error_rate=1-ac

In [ ]:
print(error_rate)

0.10526315789473684
